### PR TITLE
Bypass APF/SCOREC

### LINKED ISSUE #1: PCU_Switch_Comm requires valid MPI communicator
We cannot use MPI_UNDEFINED here because PCU requires a valid communicator:
https://github.com/SeisSol/PUMGen/blob/b1661b8bae41dd5ade38eaed0ebe282a7c9fc65f/src/input/NetCDFMesh.h#L67

Replacing MPI_UNDEFINED with 1 should do the trick.

### LINKED ISSUE #60: Converting mesh to APF fails for large mesh
I'm trying to generate a larger mesh for the texascale.
The mesh (750M cells) is created by pumgen, but there is then a bug with APF.
Might be a memory overflow, but we have 999Gb of RAM on the server (exception, and I was the only one using at the time).
 
I'm using the mesh64 branch, but this is not a new bug of this branch as I experienced it before.
(pumgen compiled with spack, with:
```spack install pumgen@mesh64 +with_simmetrix ^pumi@2.2.8 ^simmetrix-simmodsuite@2023.0-230923 ^easi jit=impalajit,lua``` (and the package modified so that it know the mesh64 version).

```
Sat Oct 07 13:09:41, Info:  No filtering enabled (contiguous storage)
Sat Oct 07 13:09:41, Info:  Using SimModSuite
Sat Oct 07 13:09:41, Info:  Loading model
Sat Oct 07 13:11:58, Info:  Extracting cases
Sat Oct 07 13:11:58, Info:  surface smoothing option: surfaceSmoothingLevel surfaceSmoothingType surfaceFaceRotationLimit Snap 1   1   5   0
Sat Oct 07 13:11:58, Info:  volume smoothing option: volumeSmoothingLevel volumeSmoothingType 1   1
Sat Oct 07 13:11:58, Info:  Activating velocity aware meshing, using 2 elements per wavelength and easi file Mw_78_Turkey_rhomulambda1D_Guvercin_et_al.yaml
Sat Oct 07 13:11:58, Info:  Adding velocity aware refinement region targeting 6 Hz, centered at x = 20000 y= 50000 z= -10000 with half sizes x = 200000 y = 100000 z = 15000
Sat Oct 07 13:11:58, Info:  rotated around z axis by  45 degree(s) counterclockwise from x axis.
Sat Oct 07 13:11:58, Info:  bypass findRegion and use group = 1
Sat Oct 07 13:11:58, Info:  Adding velocity aware refinement region targeting 0.25 Hz, centered at x = 0 y= 0 z= -15000 with half sizes x = 4e+11 y = 1.5e+11 z = 1.5e+11
Sat Oct 07 13:11:58, Info:  bypass findRegion and use group = 1
Sat Oct 07 13:11:58, Info:  Setting cases
Sat Oct 07 13:11:58, Info:  faceBound[ 96 ] = 1
Sat Oct 07 13:11:58, Info:  faceBound[ 105 ] = 1
Sat Oct 07 13:11:58, Info:  faceBound[ 95 ] = 5
Sat Oct 07 13:11:58, Info:  faceBound[ 98 ] = 5
Sat Oct 07 13:11:58, Info:  faceBound[ 107 ] = 5
Sat Oct 07 13:11:58, Info:  faceBound[ 110 ] = 5
Sat Oct 07 13:11:58, Info:  faceBound[ 119 ] = 5
Sat Oct 07 13:11:58, Info:  faceBound[ 100 ] = 65
Sat Oct 07 13:11:58, Info:  faceBound[ 93 ] = 66
Sat Oct 07 13:11:58, Info:  faceBound[ 94 ] = 66
Sat Oct 07 13:11:58, Info:  faceBound[ 108 ] = 66
Sat Oct 07 13:11:58, Info:  faceBound[ 116 ] = 66
Sat Oct 07 13:11:58, Info:  faceBound[ 121 ] = 66
Sat Oct 07 13:11:58, Info:  faceBound[ 102 ] = 67
Sat Oct 07 13:11:58, Info:  faceBound[ 109 ] = 67
Sat Oct 07 13:11:58, Info:  faceBound[ 117 ] = 67
Sat Oct 07 13:11:58, Info:  faceBound[ 111 ] = 68
Sat Oct 07 13:11:58, Info:  faceBound[ 94 ] = 68
Sat Oct 07 13:11:58, Info:  faceBound[ 112 ] = 69
Sat Oct 07 13:11:58, Info:  globalMSize = 5000
Sat Oct 07 13:11:58, Info:  face id: 100 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 93 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 94 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 108 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 116 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 121 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 102 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 109 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 117 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 111 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 94 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 112 , MSize = 200
Sat Oct 07 13:11:58, Info:  face id: 105 , MSize = 900
Sat Oct 07 13:11:58, Info:  Enabling velocity aware meshing
Sat Oct 07 13:11:58, Info:  Target equivolume AspectRatio = 12
Sat Oct 07 13:11:58, Info:  Target equiarea AspectRatio = 6
Sat Oct 07 13:11:58, Info:  Starting the surface mesher
Sat Oct 07 13:11:58, Info:  Progress: Surface Meshing
Sat Oct 07 13:29:02, Info:  Progress: Adapting Mesh
Sat Oct 07 13:30:04, Info:  Progress: Surface Mesh Improver
Sat Oct 07 13:30:04, Info:  Progress: Surface Mesh Improvement , 0 / 2
Sat Oct 07 13:30:04, Info:  Progress: Surface Mesh Improvement , 1 / 2
Sat Oct 07 13:30:04, Info:  Progress: Surface Mesh Improvement , 2 / 2
Sat Oct 07 13:30:04, Info:  Progress: Surface Mesh Improvement , done
Sat Oct 07 13:30:04, Info:  Progress: Surface Smoothing , 0 / 100
Sat Oct 07 13:30:04, Info:  Progress: Surface Smoothing , 16 / 100
Sat Oct 07 13:30:04, Info:  Progress: Surface Smoothing , 32 / 100
Sat Oct 07 13:30:04, Info:  Progress: Surface Smoothing , done
Sat Oct 07 13:30:04, Info:  Progress: Fix Surface Intersections
Sat Oct 07 13:30:15, Info:  Starting the volume mesher
Sat Oct 07 13:30:15, Info:  Progress: Volume Meshing
Sat Oct 07 13:30:15, Info:  Progress: Creating volume mesh
Sat Oct 07 13:49:58, Info:  Progress: Adapting Mesh
Sat Oct 07 13:50:09, Info:  Progress: Volume Mesh Improver
Sat Oct 07 13:50:09, Info:  Progress: Volume Optimization
Sat Oct 07 13:50:30, Info:  Progress: Volume Smoothing , 0 / 100
Sat Oct 07 13:50:32, Info:  Progress: Volume Smoothing , 5 / 100
Sat Oct 07 13:50:35, Info:  Progress: Volume Smoothing , 10 / 100
Sat Oct 07 13:50:37, Info:  Progress: Volume Smoothing , 15 / 100
Sat Oct 07 13:50:39, Info:  Progress: Volume Smoothing , 20 / 100
Sat Oct 07 13:50:42, Info:  Progress: Volume Smoothing , 25 / 100
Sat Oct 07 13:50:44, Info:  Progress: Volume Smoothing , 30 / 100
Sat Oct 07 13:50:47, Info:  Progress: Volume Smoothing , 35 / 100
Sat Oct 07 13:50:49, Info:  Progress: Volume Smoothing , 40 / 100
Sat Oct 07 13:50:51, Info:  Progress: Volume Smoothing , 45 / 100
Sat Oct 07 13:50:53, Info:  Progress: Volume Smoothing , 50 / 100
Sat Oct 07 13:50:55, Info:  Progress: Volume Smoothing , 55 / 100
Sat Oct 07 13:50:57, Info:  Progress: Volume Smoothing , 60 / 100
Sat Oct 07 13:50:59, Info:  Progress: Volume Smoothing , 65 / 100
Sat Oct 07 13:51:01, Info:  Progress: Volume Smoothing , 70 / 100
Sat Oct 07 13:51:03, Info:  Progress: Volume Smoothing , 75 / 100
Sat Oct 07 13:51:05, Info:  Progress: Volume Smoothing , 80 / 100
Sat Oct 07 13:51:06, Info:  Progress: Volume Smoothing , 85 / 100
Sat Oct 07 13:51:08, Info:  Progress: Volume Smoothing , 90 / 100
Sat Oct 07 13:51:11, Info:  Progress: Volume Smoothing , 95 / 100
Sat Oct 07 13:52:09, Info:  Progress: Volume Smoothing , done
Sat Oct 07 13:52:13, Info:  AR statistics:
Sat Oct 07 13:52:22, Info:  AR max: 19.1125
Sat Oct 07 13:52:22, Info:  AR (target: < ~10):
Sat Oct 07 13:52:22, Info:    [ 0.00 , 2.00 ): 593524
Sat Oct 07 13:52:22, Info:    [ 2.00 , 4.00 ): 728855697
Sat Oct 07 13:52:22, Info:    [ 4.00 , 6.00 ): 22308449
Sat Oct 07 13:52:22, Info:    [ 6.00 , 10.00 ): 2083036
Sat Oct 07 13:52:22, Info:    [ 10.00 , 20.00 ): 30302
Sat Oct 07 13:52:22, Info:    [ 20.00 , 40.00 ): 0
Sat Oct 07 13:52:22, Info:    [ 40.00 , 100.00 ): 0
Sat Oct 07 13:52:22, Info:    [ 100.00 ,inf): 0
Sat Oct 07 13:52:24, Info:  Converting mesh to APF
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 33 with PID 0 on node exception exited on signal 9 (Killed).
--------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by davschneller**
This PR adds functionality requested in #60 , where we had problems with the APF module. Thus, this PR makes it superfluous—we got all information at our fingertips already. So far, it's mostly tested with Simmodeler version 2023.0-231002. Also, all other mesh formats (excluding APF itself) now don't use the APF module anymore—a Simmodeler variant which still falls back to APF still exists here, though.

Changes:

* compile without SCOREC core present (it can still be compiled in over a flag `SCOREC` in CMake, but it will only enable support for APF native and Simmodeler with APF—the other formats will not change back to using APF then)
* readers without APF for msh2, msh4, gambit, netcdf, simmodsuite
* bugfix when using msh2, msh4, gambit with little elements per rank
* improved support for large-scale meshes (msh4 has been reported to work with over 1 bln elements, cf. https://github.com/SeisSol/SeisSol/discussions/955#discussioncomment-9236284 )
* add boundary format attribute to each file
* (breaking) removed support for the fidap mesh format
* (breaking) removed option for VTK or APF dumps; loss of some sanity check functions provided by APF

### CODE REVIEW

**Comment by davschneller** [comment]
Also, for completeness:

Fixes #60 
Fixes #1 

(the latter, since we won't use PCU in the NetCdf parser anymore)

File: src/aux/MPIConvenience.cpp [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+#include <limits>
+#include <mpi.h>
+#include <vector>
+
+namespace {
+constexpr std::size_t DataIncrement = std::numeric_limits<int>::max();
+constexpr int Tag = 1000;
+
+std::vector<MPI_Request> largeIsend(const void* sendbuf, std::size_t sendsize, std::size_t senddisp,
+                                    MPI_Datatype sendtype, int dest, int tag, MPI_Comm comm) {
```
Comment (Thomas-Ulrich) [inline src/aux/MPIConvenience.cpp:11]: Can you add a comment explaining in which way largeIsend differs from Isend and why it is needed? In the end, it is an extension of Isend to std::size_t?

File: src/aux/InsphereCalculator.cpp [hunk 2]
```diff
@@ -0,0 +1,165 @@
+#include "InsphereCalculator.h"
```
Comment (Thomas-Ulrich) [inline src/aux/InsphereCalculator.cpp:1]: I guess you don't use the one from seissol:
https://github.com/SeisSol/SeisSol/blob/dd018b3398258a23ec2a33c74bd7f31b503dcca6/src/Initializer/time_stepping/GlobalTimestep.cpp#L22-L32
because you want to avoid another dependency?

**Review by Thomas-Ulrich — APPROVED** [review]
LGTM, based on my understanding

File: src/aux/MPIConvenience.cpp (hunk 1 above)
Comment (davschneller) [reply src/aux/MPIConvenience.cpp:11]: Yes; exactly. That's all it is, basically. We run multiple `Isend`s, if the data is larger than the integer limit.

Other methods to handle that would have been to use extra data types.

File: src/aux/InsphereCalculator.cpp (hunk 2 above)
Comment (davschneller) [reply src/aux/InsphereCalculator.cpp:1]: Yup—that was the main thing. Though it probably wouldn't be a big one anyways... I.e. it's thinkable I'd say.

IIRC I copied the calculation from there.

File: src/aux/MPIConvenience.cpp (hunk 1 above)
Comment (davschneller) [reply src/aux/MPIConvenience.cpp:11]: However, the actual main reason all these extra methods are needed are the offsets—i.e. to have a scatter/alltoall that is _in total_ larger than the integer limit. Usually, we don't cross the integer boundary for a single send, i.e. the `largeIsend`/`largeIrecv` is more secondary.
